### ISSUE TITLE
Feature audit: Prescriptions

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#29]
## New patterns

**1. Sorting mechanism**
   - Desktop: list of links 
> <img width="438" alt="screen shot 2016-11-28 at 10 45 25 am" src="https://cloud.githubusercontent.com/assets/4106356/20681374/3ecf5010-b558-11e6-9e1f-2b5b8688b8dc.png">

   - Mobile: dropdown
   > <img width="383" alt="screen shot 2016-11-28 at 10 45 30 am" src="https://cloud.githubusercontent.com/assets/4106356/20681376/43cbb874-b558-11e6-9e26-3799a65153ac.png">

**2. Definition card - more complex layout**

> <img width="494" alt="screen shot 2016-11-28 at 10 53 17 am" src="https://cloud.githubusercontent.com/assets/4106356/20681541/e4f3dc5e-b558-11e6-984d-df71ba384c97.png">

**3. Section headings within a list**

   - Prescriptions list:
> <img width="467" alt="screen shot 2016-11-28 at 11 08 30 am" src="https://cloud.githubusercontent.com/assets/4106356/20682048/2077a5ec-b55b-11e6-80e1-e03c8e0faa17.png">

   - Glossary:
> <img width="499" alt="screen shot 2016-11-28 at 11 23 14 am" src="https://cloud.githubusercontent.com/assets/4106356/20682487/16123eee-b55d-11e6-950b-b839061740c1.png">

**4. Back link**
> <img width="483" alt="screen shot 2016-11-28 at 11 13 57 am" src="https://cloud.githubusercontent.com/assets/4106356/20682183/d02df392-b55b-11e6-9208-80f868ad684c.png">

## Inconsistencies / bugs

1. Sorting mechanisms refill and history tabs are missing "Sort by" label on mobile
2. Pagination and back link arrows should use proper unicode `›` `‹` carats, not `<` `>`characters
3. Refill history - label for "last submit date" turns into "last requested date" on mobile, even though the option to sort by is still called "last submit date"
4. Breadcrumb link is above the glossary page heading, but below the prescription detail page heading
> <img width="469" alt="screen shot 2016-11-28 at 11 59 58 am" src="https://cloud.githubusercontent.com/assets/4106356/20683807/4580d2da-b562-11e6-8fff-1ff235910a6d.png">
5. Prescription detail page main column width is smaller than standard templates - content doesn't take up full 12 columns
> <img width="1001" alt="refill_your_prescriptions__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20683908/9e3d8b7a-b562-11e6-859c-bfaa6903dfe8.png">
6. Refill button on detail page - 100% width for buttons on desktop isn't used anywhere else
> <img width="468" alt="screen shot 2016-11-28 at 12 07 39 pm" src="https://cloud.githubusercontent.com/assets/4106356/20684100/70e00814-b563-11e6-8fe6-40c1a2e084a3.png">
7. Order History section heading doesn't use h2 `va-h-ruled` style used in other section headings in Rx
> <img width="487" alt="screen shot 2016-11-28 at 12 09 54 pm" src="https://cloud.githubusercontent.com/assets/4106356/20684155/a3599bb6-b563-11e6-81c0-35abfd5286d7.png">

## For discussion

1. Labels (see definition card above) - in some apps these are bold (profile, claim status), here they are not. Can we standardize on an approach?
2. Use of all caps should go away - more difficult to read
   - Prescription names
3. Back link vs. breadcrumbs - is it acceptable to use either/or based on context, or should we standardize on breadcrumbs?
4. (Related to breadcrumbs) Page headings - right now a prescription detail page has 2 headings - first "Prescriptions" to contextualize where you are, then the name of the prescription. Could have just the prescription name as the main heading if breadcrumbs were present to create context.
   - Secure messaging should be considered in this context too - uses the same dynamic.
5. Two different section heading styles in vets.gov
   - Smaller h4 `highlight` that appears in [sidebars](https://www.vets.gov/employment/job-seekers/) and in sections in Claim Status
   - Larger h2 `va-h-ruled` appearing in prescriptions (prescriptions list, glossary, prescription detail sidebar) and [employment](https://www.vets.gov/employment/)
6. Glossary page headings need better hierarchy - sections & individual terms are the same size
7. Refill history sort mechanism doesn't have the ability to change between ascending/descending order on mobile
8. How are we determining which types of links are represented as a text link vs. a button? Seems like  "message provider" link here should be a button
> <img width="492" alt="refill_your_prescriptions__vets_gov 2" src="https://cloud.githubusercontent.com/assets/4106356/20686837/06b91078-b56f-11e6-969d-8cb0be332685.png">

**Comment by gnakm** [comment]
Inconsistencies / bugs

Sorting mechanisms refill and history tabs are missing "Sort by" label on mobile
Section headings don't match those used elsewhere - see https://www.vets.gov/employment/job-seekers/
Pagination and back link arrows should use proper unicode › ‹ carats, not < >characters
Refill history - label for "last submit date" turns into "last requested date" on mobile, even though the option to sort by is still called "last submit date"
Breadcrumb link is above the glossary page heading, but below the prescription detail page heading

**Comment by gnakm** [comment]
Inconsistencies / bugs

Sorting mechanisms refill and history tabs are missing "Sort by" label on mobile
Section headings don't match those used elsewhere - see https://www.vets.gov/employment/job-seekers/
Pagination and back link arrows should use proper unicode › ‹ carats, not < >characters
Refill history - label for "last submit date" turns into "last requested date" on mobile, even though the option to sort by is still called "last submit date"
Breadcrumb link is above the glossary page heading, but below the prescription detail page heading

**Comment by gnakm** [comment]
@mel Thanks for the thorough audit. I reviewed inconsistencies/bugs #1-8. Noticed most of those as well and will make issues for each one. The discussions include a lot of them. Please let me know if you already made any issues so we don't have duplicates. 

Left my comments in bold.

- Labels (see definition card above) - in some apps these are bold (profile, claim status), here they are not. Can we standardize on an approach? **Could you show me which definition cards you are talking about?**
- Use of all caps should go away - more difficult to read - **We've addressed this and it all depends on how the data is entered from the clinician's end.** 
- Back link vs. breadcrumbs - is it acceptable to use either/or based on context, or should we standardize on breadcrumbs? **For more context, we decided on back to list because you can land on the glossary page and detail page from both refill and history page. I think standardizing on breadcrumb would probably be more helpful incase users get lost and want to know where they are. We may have to test this.** 
- Related to breadcrumbs ^ Page headings - right now a prescription detail page has 2 headings - first "Prescriptions" to contextualize where you are, then the name of the prescription. Could have just the prescription name as the main heading if breadcrumbs were present to create context.
**I like the prescription name being main heading.**
- Two different section heading styles in vets.gov
  - Smaller h4 highlight that appears in sidebars and in sections in Claim Status
  - Larger h2 va-h-ruled appearing in prescriptions (prescriptions list, glossary, prescription detail sidebar) and employment
**I think we should make the h4 all across Vets.gov**
- Glossary page headings need better hierarchy - sections & individual terms are the same size
**Glossary should be `h1`, Status headers `h2`, Definition headers `h3`**
- Refill history sort mechanism doesn't have the ability to change between ascending/descending order on mobile **Will make issue**
- How are we determining which types of links are represented as a text link vs. a button? Seems like "message provider" link here should be a button
**You're right they should. I think text link was because the cards were getting too big.**

**Comment by melwoodard** [comment]
Thank you @gnakm ! I haven't created any additional issues, I'll let you handle them so we don't duplicate work.

Re: labels, I was referring to the grey prescription cards. The labels here are the same font-weight as the values to their right, but in other contexts in Rx and other apps, the labels are bold next to regular-weight values.

<img width="494" alt="e4f3dc5e-b558-11e6-984d-df71ba384c97" src="https://cloud.githubusercontent.com/assets/4106356/20692205/391da350-b58b-11e6-9308-945f8a7e3b95.png">

I agree with all of your comments above - do you want to handle any design issues from that list that may need mockups?

**Comment by gnakm** [comment]
@melwoodard Yup! I will put together mocks. Will let you know if I have any other questions.

**Comment by gnakm** [comment]
@melwoodard What are your thoughts on having an H2 option with a border bottom? I could see the case for us need versions with border bottoms because they separate pages. It will definitely get the Rx glossary page. We also have it for FL as well https://www.vets.gov/facilities/facility/vba_372 . It helps break out the pages more. Thoughts?

**Comment by melwoodard** [comment]
@gnakm I agree there's a case for it, we used the same type of pattern in claim status to break up sections on the files tab. I think we just need to standardize on one style and use it in a consistent way. On claims it's an H4, and may make sense to bump it up to an H2/H3 based on the type of hierarchy complexity seen in the glossary.

<img width="1024" alt="screen shot 2016-11-30 at 8 59 40 am" src="https://cloud.githubusercontent.com/assets/4106356/20762497/63974bb2-b6db-11e6-87a6-2d4cef6e12d7.png">
