### ISSUE TITLE
Feature audit: Facility Locator

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#32]
## New patterns

**1. Custom dropdown with legend icons**
> <img width="249" alt="screen shot 2016-11-29 at 11 56 31 am" src="https://cloud.githubusercontent.com/assets/4106356/20726790/dd276a9e-b62b-11e6-8df9-5a26706f8d3d.png">

**2. Disabled text field state**
> <img width="248" alt="screen shot 2016-11-29 at 12 04 08 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726815/f270b770-b62b-11e6-9af0-4576d617e2ee.png">

**3. Boundary around an application 'chrome'**
> <img width="1016" alt="screen shot 2016-11-29 at 12 04 23 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726845/0c43932a-b62c-11e6-9383-e6a161b09ad1.png">

**4. Outline alert message style**
> <img width="654" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727621/16d4fa56-b62f-11e6-8261-d1a2d35758fe.png">

**5. Contact links with icons**
> <img width="156" alt="screen shot 2016-11-29 at 12 23 49 pm" src="https://cloud.githubusercontent.com/assets/4106356/20727534/b9424984-b62e-11e6-99ba-4c7111145738.png">

**6. Self-contained scrolling list**
> <img width="350" src="https://cloud.githubusercontent.com/assets/4106356/20727662/3e7964ca-b62f-11e6-84df-763ce27f7ef6.png">

## Inconsistencies / bugs

1. Page headings are `h3` - should be `h1`

2. Dropdowns are missing ^ carat when opened
> <img width="249" alt="screen shot 2016-11-29 at 11 56 31 am" src="https://cloud.githubusercontent.com/assets/4106356/20726544/e90712ca-b62a-11e6-8d1a-c1dcdbb11e11.png">

3. Page heading isn't flush left with the rest of the content
> <img width="450" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20726755/bdb5f388-b62b-11e6-82e3-2a62ef213481.png">

4. Contact / directions links should be underlined to match the standard text link style
> <img width="301" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727057/dac27e96-b62c-11e6-8785-cd56e2b1b26a.png">

5. Back link uses a different carat icon than seen in Rx, SM
> <img width="151" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727196/6a35fe72-b62d-11e6-936e-47f5d9593789.png">

6. Sidebar heading should use `h4 highlight` class
> <img width="339" alt="screen shot 2016-11-29 at 12 16 44 pm" src="https://cloud.githubusercontent.com/assets/4106356/20727313/d8fdb868-b62d-11e6-8e5b-f645d1f26b06.png">

7. Mobile tabs are different than style in Rx, Claims
> <img width="311" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727890/0e4dde42-b630-11e6-99f5-9ff7ae3c7712.png"> <img width="301" alt="screen_shot_2016-11-28_at_10_39_37_am" src="https://cloud.githubusercontent.com/assets/4106356/20727899/174cb022-b630-11e6-8dc1-8fdb542b59c8.png">

8. Truncation in the Service Type dropdown is too severe - still room for ~8 more characters (more on full-width mobile view)
> <img width="246" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727984/79c357c4-b630-11e6-8415-d92dfcddf68a.png">

## For discussion

1. Is there reason for the grey background around the search chrome? Secure messaging's search / navigation functions don't have one - should these two align more in their visual treatment?
> <img width="1016" alt="screen shot 2016-11-29 at 12 04 23 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726886/3b062aba-b62c-11e6-954c-3198d6f5a867.png">

> <img width="795" alt="screen shot 2016-11-29 at 12 06 49 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726912/552b52a8-b62c-11e6-8e0e-71a2b0b641ae.png">

2. Another instances of bolding / not bolding with labels, but this time in reverse - the label is regular, the value is bold. Don't know what the solution is here, but adding this to the plate
> <img width="328" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727027/b482509e-b62c-11e6-9a28-04a9726f1c20.png">

3. Back link vs. breadcrumbs - while a "back to results" link is very useful for search, having it below the breadcrumbs seems to clash - plus the breadcrumbs should also list the current page, in this case Tahoma National Cemetery.
> <img width="406" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727156/3f975058-b62d-11e6-8383-ffbf447c5647.png">

4. Should website and directions links use the <img width="18" alt="apply_for_va_health_care__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727243/96741622-b62d-11e6-8f17-644b5981ffb9.png"> external link icon? 
> <img width="165" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727231/8e9c45a0-b62d-11e6-843b-9db9e19f240c.png">

5. Disclaimer - should this use the yellow alert style? (documented [here](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28))
> <img width="666" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727395/3061c2ca-b62e-11e6-9534-42e14bf2f7e1.png">

6. Location detail pages could benefit from more spacing to separate sections and types of content
> <img width="568" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727459/69b8ebfc-b62e-11e6-9adb-9143bf26b07f.png">

**Comment by melwoodard** [comment]
@gnakm @NatalieEMoore I'm working through an audit of all the new features we've released to capture new UI patterns and manage consistency. Would love your feedback on the inconsistencies / for discussion sections above. I haven't looked at any of the existing FL bugs, so some of these may have already been captured in issues. Thanks!

**Comment by NatalieEMoore** [comment]
@melwoodard 1-8 for bugs looks correct, they are bugs.  I can add separate issues on the vets.gov/website repo if that makes the most sense @gnakm?

for discussion, # 5, I do think the disclaimer should be the same across the site so adding yellow may be a good idea.

**Comment by gnakm** [comment]
@melwoodard Thank you for another thorough audit. I filed most of the bugs. Please check my thoughts in bold! 

## Inconsistencies / bugs

1. Page headings are `h3` - should be `h1` [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4182)

2. Dropdowns are missing ^ carat when opened [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4180)

3. Page heading isn't flush left with the rest of the content [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4183)

4. Contact / directions links should be underlined to match the standard text link style
**So the hover gets really... not so pretty with the icon. What are your thoughts on just underlining the the numbers and not making the label clickable?**

Right now:
<img width="281" alt="screen shot 2016-12-01 at 10 57 21 am" src="https://cloud.githubusercontent.com/assets/13420618/20801778/f7984a82-b7b7-11e6-9c04-d6a2d089150b.png">

Possbility?
<img width="609" alt="screen shot 2016-12-01 at 11 21 46 am" src="https://cloud.githubusercontent.com/assets/13420618/20801927/6456fe48-b7b8-11e6-958d-4abf59ad563e.png">


5. Back link uses a different carat icon than seen in Rx, SM _Related to no. 3 in discussion section below_

6. Sidebar heading should use `h4 highlight` class [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4182)

7. Mobile tabs are different than style in Rx, Claims [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4184)

8. Truncation in the Service Type dropdown is too severe - still room for ~8 more characters (more on full-width mobile view) [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4185)


## For discussion

1. Is there reason for the grey background around the search chrome? Secure messaging's search / navigation functions don't have one - should these two align more in their visual treatment?
> <img width="1016" alt="screen shot 2016-11-29 at 12 04 23 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726886/3b062aba-b62c-11e6-954c-3198d6f5a867.png">
> <img width="795" alt="screen shot 2016-11-29 at 12 06 49 pm" src="https://cloud.githubusercontent.com/assets/4106356/20726912/552b52a8-b62c-11e6-8e0e-71a2b0b641ae.png">

**We actually tried it without the filled in color and there wasn't enough contrast, especially with the map on desktop. Not sure if this has to align with secure messaging. I see it more as each tool need slightly different treatment for visual balance on the page.** 

2. Another instances of bolding / not bolding with labels, but this time in reverse - the label is regular, the value is bold. Don't know what the solution is here, but adding this to the plate

Another thing we went back and forth on but glad you flagged it now that we have more tools. 
[Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4187)

3. Back link vs. breadcrumbs - while a "back to results" link is very useful for search, having it below the breadcrumbs seems to clash - plus the breadcrumbs should also list the current page, in this case Tahoma National Cemetery.
> <img width="406" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727156/3f975058-b62d-11e6-8383-ffbf447c5647.png">

**I think we should get rid of back link the way we aiming to do for Rx and add title of Facility location in breadcrumb. @melwoodard  Let me know what you think and I'll file an issue.**

<img width="681" alt="screen shot 2016-12-01 at 11 14 52 am" src="https://cloud.githubusercontent.com/assets/13420618/20801627/8c03e3c6-b7b7-11e6-9f04-01cb80848d38.png">

4. Should website and directions links use the <img width="18" alt="apply_for_va_health_care__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727243/96741622-b62d-11e6-8f17-644b5981ffb9.png"> external link icon? 

**Yes it should!** [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4186)

5. Disclaimer - should this use the yellow alert style? (documented [here](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28))
> <img width="666" alt="facility_locator__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20727395/3061c2ca-b62e-11e6-9534-42e14bf2f7e1.png">

**Context: We went back and forth on this because when we had it as the blue information alert box, users missed it. It's actually an on going problem we have with the blue information call out box all across Vets.gov. A handful of us agreed that the white box was a lot easier to see but we actually never tested it.**  @NatalieEMoore **I think we talked about how this is not really an alert but informational. I defer to you. If yellow box makes more sense, I will file an issue!**

6. Location detail pages could benefit from more spacing to separate sections and types of content

**Agreed! I think Ben was using the same components for results listing for detail page but we should definitely tweak this.** [Filed issue here](https://github.com/department-of-veterans-affairs/vets-website/issues/4188)

**Comment by melwoodard** [comment]
Thanks Gina! 

- Contact info - making just the phone numbers link makes sense to me. In that case the labels for "main number" etc should probably also be bold for consistency.
- Back link vs. breadcrumbs - agreed to standardize on breadcrumbs
- Disclaimer alert style - I think the difficulty is that while it's not intended as an alert, the icon still makes it feel that way. The issue with a blue box is it gets overlooked, and the concern with a yellow box is it could be too strong. How would you judge the relative importance of seeing this messaging? Do you think we could get away with just bold text rather than pulling it out into a box?

**Comment by melwoodard** [comment]
Update: @gnakm ok, I'm gaining some sympathy for the outlined box :)

I'm finding a similar scenario in the alert we're adding for signing into Rx/SM about needing an MHV account. A yellow alert feels too strong here, and potentially annoying since a returning user could use this path regularly to get to the Rx / SM apps (rather than sign in through the nav).

Thoughts? 

![image](https://cloud.githubusercontent.com/assets/4106356/20819003/5abd09ee-b7e6-11e6-8c68-d3cc181cd04d.png)

**Comment by NatalieEMoore** [comment]
For  number 5:  Gina wrote, "Context: We went back and forth on this because when we had it as the blue information alert box, users missed it. It's actually an on going problem we have with the blue information call out box all across Vets.gov. A handful of us agreed that the white box was a lot easier to see but we actually never tested it. @NatalieEMoore I think we talked about how this is not really an alert but informational. I defer to you. If yellow box makes more sense, I will file an issue!"

Can we do testing? I think it's both an alert and information.  How is it being shown across the site currently? @gnakm @melwoodard

**Comment by melwoodard** [comment]
I think testing would be valuable - another thing to think about in the case of FL is the placement of the alert. I can see how it could easily be dismissed as an ad or something irrelevant when it's toward the end of the content.

We're using the blue background style across the site, in two flavors - a short and sweet banner with the (i) icon used for brief alerts, and a lengthier callout used to explain eligibility for a particular benefit.

Alert:

![image](https://cloud.githubusercontent.com/assets/4106356/20893773/d2c77fee-bac7-11e6-9a44-2ef61e03d7c0.png)

Eligibility:

![image](https://cloud.githubusercontent.com/assets/4106356/20893876/2f48769c-bac8-11e6-89e5-3bbe5a0c680b.png)

**Comment by gnakm** [comment]
Notes from usability testing when we tested with blue box:
**Theme:** The call out box on the facility details page was consistently missed or skipped
**Recommendations:** Do have a list of known services on each detail page, along with a message (not in a call out box) about why not everything is there, and what to do to find out.

https://github.com/department-of-veterans-affairs/vets.gov-research/blob/master/Projects/FacilityFinder-Login_10-13-2016/FacilityLocator-Login-SummaryFindings.md

**Comment by gnakm** [comment]
@melwoodard How about using the white box with outline for informational call outs? I think they stand out more and I agree, looks less like an ad. 

Current:

<img width="674" alt="screen shot 2016-12-05 at 2 56 33 pm" src="https://cloud.githubusercontent.com/assets/13420618/20900815/be785eec-bafd-11e6-96bb-20569dc23244.png">

Potential:

<img width="684" alt="screen shot 2016-12-05 at 2 55 05 pm" src="https://cloud.githubusercontent.com/assets/13420618/20900837/cc942114-bafd-11e6-8ec0-ab0381b3e5fa.png">

I think leaving the blue for longer content works because it works better in a long body of text. It's more a matter of making sure that we have consistent information in those boxes (i.e. are you eligible? Who is covered).
