### ISSUE TITLE
Loader message

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets.gov-patterns#33]
We currently have different ways of showing the loading message across Rx, SM, FL and Tracking-Claims. 

Rx and SM have to take out "is"
Claims needs to add "..." at the end of the line

**Font size** 24
**Color**: Primary Darkest (Hex value: #112e51)

There are samples from Rx and SM:
<img width="342" alt="99033374-afd3-11e6-8889-a933cac26a51" src="https://cloud.githubusercontent.com/assets/13420618/20765818/f618618a-b701-11e6-8442-abf9218982d4.png">

<img width="341" alt="9908cb7c-afd3-11e6-98ed-aa27c3e7000d" src="https://cloud.githubusercontent.com/assets/13420618/20765824/007620e0-b702-11e6-8b78-0932ac116d00.png">

@melwoodard Could you review this?
cc: @suzchap @angel for awareness

**Comment by melwoodard** [comment]
@gnakm looks good! We also have this other type of loading indicator that appears when I load the facility locator. It doesn't seem like FL needs very specific text here, especially since it's quick to load. I'm in favor of a generic "Loading..." message, which could be applied by default anywhere else that doesn't need something super specific.

![screen shot 2016-12-02 at 9 23 43 am](https://cloud.githubusercontent.com/assets/4106356/20843674/1a0c3286-b871-11e6-850e-9750878dcff2.png)

**Comment by suzchap** [comment]
@melwoodard has this been resolved and can be closed or does it need to go into the nebula backlog?

**Comment by melwoodard** [comment]
This hasn't been resolved yet. I've copied it to vets.gov-team and will close this issue.
